---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  - name: check if welcome.conf exists or not
    stat: 
     path: /etc/httpd/conf.d/welcome.conf
    register: welcome
  - name: Rename WebServer file
    command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.off
    when: welcome.stat.exists == True
    notify: restart apache
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
